version: '3.6'
services:
  # Wordpress auto configuration
  # depends on wp-cli build
  wp-auto-config:
    image: wpcli
    build: ../backend/wordpress/landing-page/wpcli/
    container_name: wp_autoconfig
    entrypoint: sh -c "/wait && make -f /scripts/Makefile"
    volumes:
      - ../backend/wordpress/landing-page/dist:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - wordpress-landing-page
      - mysql
    environment:
      # Waiting for MySQL and wordpress -------------------
      - WAIT_HOSTS=mysql:3306,wordpress-landing-page:80
      - WAIT_BEFORE_HOSTS=${WAIT_BEFORE_HOSTS:-10}
      - WAIT_AFTER_HOSTS=${WAIT_AFTER_HOSTS:-5}
      - WAIT_HOSTS_TIMEOUT=${WAIT_HOSTS_TIMEOUT:-300}
      - WAIT_SLEEP_INTERVAL=${WAIT_SLEEP_INTERVAL:-30}
      - WAIT_HOST_CONNECT_TIMEOUT=${WAIT_HOST_CONNECT_TIMEOUT:-30}
      # Wordpress configuration -----------------------------
      - WORDPRESS_LOCALE=en_US
      - WORDPRESS_DB_NAME=wp-landing-page
      - WORDPRESS_TABLE_PREFIX=landingPage_
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=${DATABASE_USER:-admin}
      - WORDPRESS_DB_PASSWORD=${DATABASE_PASSWORD:-password}
      - WORDPRESS_WEBSITE_TITLE=landing-page
      - WORDPRESS_WEBSITE_POST_URL_STRUCTURE="/blog/%postname%/"
      - WORDPRESS_ADMIN_USER=wordpress
      - WORDPRESS_ADMIN_PASSWORD=wordpress
      - WORDPRESS_ADMIN_EMAIL="test@example.com"
