version: "3.7"
services:
  proxy:
    image: traefik:latest
    container_name: traefik
    ports:
      - 80:80 # Exposes port 80 for incomming web requests
      - 443:443
      - 8080:8080  # The Web UI port http://0.0.0.0:8080 (enabled by --api.insecure=true)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # So that Traefik can listen to the Docker events
      - ./letsencrypt:/letsencrypt # Copies the Let's Encrypt certificate locally for ease of backing up
      - ../backend/proxy/traefik-entrypoints.yml:/etc/traefik/traefik.yml # Mounts the Traefik static configuration inside the Traefik container

  # Error Page service
  error:
    image: guillaumebriday/traefik-custom-error-pages
    depends_on:
      - proxy
    labels:
      - traefik.enable=true
      # Routers
      # - traefik.http.routers.error.rule=Host(`error.localhost`)
      - traefik.http.routers.error.service=error
      - traefik.http.routers.error.entrypoints=web
      # Services
      - traefik.http.services.error.loadbalancer.server.port=80