version: "3.7"
services:
  frontend-style-guide:
    build:
      context: ../frontend/frontend-style-guide
      dockerfile: frontend-style-guide.Dockerfile
    container_name: frontend-style-guide
    depends_on:
      - proxy
    volumes:
      - ../frontend/frontend-style-guide/dist:/usr/src/app/dist
      - ../frontend/frontend-style-guide/stories:/usr/src/app/stories
      - ../frontend/frontend-style-guide/wiki:/usr/src/frontend-style-guide/wiki
      - ../frontend/frontend-style-guide/.storybook:/usr/src/frontend-style-guide/.storybook
      - /usr/src/app/node_modules
    labels:
      - traefik.enable=true
      # Routers
      # - traefik.http.routers.storybook.rule=Host(`storybook.localhost`)
      - traefik.http.routers.frontend-style-guide.entrypoints=web
      - traefik.http.routers.frontend-style-guide.entrypoints=websecure
      - traefik.http.routers.frontend-style-guide.tls.certresolver=myresolver
      # Services
      - traefik.http.services.frontend-style-guide.loadbalancer.server.port=6006
      # Middlewares
      - traefik.http.routers.frontend-style-guide.middlewares=test-compress
      # Compress Middleware
      - traefik.http.middlewares.test-compress.compress=true
      # Error Pages Middleware
      - traefik.http.middlewares.test-errorpages.errors.status=400-599
      - traefik.http.middlewares.test-errorpages.errors.service=error
      - traefik.http.middlewares.test-errorpages.errors.query=/{status}.html
      # Redirect Scheme HTTP -> HTTPS
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.port=443


