version: "3.7"
services:
  prototype:
    build:
      context: ../frontend/static/prototype
      dockerfile: prototype.Dockerfile
    container_name: prototype
    depends_on:
      - proxy
    volumes:
      - ../frontend/static/prototype/dist:/var/www/html
    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.prototype.entrypoints=web
      - traefik.http.routers.prototype.entrypoints=websecure
      - traefik.http.routers.prototype.tls.certresolver=myresolver
      # Services
      - traefik.http.services.prototype.loadbalancer.server.port=80
      # Middlewares
      - traefik.http.routers.prototype.middlewares=test-compress
      # Compress Middleware
      - traefik.http.middlewares.test-compress.compress=true
      # Error Pages Middleware
      - traefik.http.middlewares.test-errorpages.errors.status=400-599
      - traefik.http.middlewares.test-errorpages.errors.service=error
      - traefik.http.middlewares.test-errorpages.errors.query=/{status}.html
      # Redirect Scheme HTTP -> HTTPS
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.port=443