version: "3.7"
services:
  wordpress-landing-page:
    build:
      context: ../backend/wordpress/landing-page
      dockerfile: landing-page.Dockerfile
    container_name: wordpress-landing-page
    volumes:
      # php config
      - ../backend/wordpress/landing-page/php/php.conf.ini:/usr/local/etc/php/conf.d/php.ini
      # TODO: add bindings as neccessary
      # ../backend/wordpress/landing-page/plugins/* !!(vendor -> plugins && mu-plugins -> mu-plugins):/var/www/html/wp-content
      # ../backend/wordpress/landing-page/required/* !!(bind file by file):/var/www/html/wp-content/themes/landing-page
      - ../backend/wordpress/landing-page/dist:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=wp-landing-page
      - WORDPRESS_TABLE_PREFIX=landingPage_
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=${DATABASE_USER:-admin}
      - WORDPRESS_DB_PASSWORD=${DATABASE_PASSWORD:-password}
    restart: always
    depends_on:
      - proxy
      - mysql
    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.wordpress-landing-page.entrypoints=web
      - traefik.http.routers.wordpress-landing-page.entrypoints=websecure
      - traefik.http.routers.wordpress-landing-page.tls.certresolver=myresolver
      # Middlewares
      - traefik.http.routers.wordpress-landing-page.middlewares=test-compress
      # Compress Middleware
      - traefik.http.middlewares.test-compress.compress=true
      # Error Pages Middleware
      - traefik.http.middlewares.test-errorpages.errors.status=400-599
      - traefik.http.middlewares.test-errorpages.errors.service=error
      - traefik.http.middlewares.test-errorpages.errors.query=/{status}.html
      # Redirect Scheme HTTP -> HTTPS
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.port=443

  mysql:
    build:
      context: ../backend/database/mysql
      dockerfile: mysql.Dockerfile
    container_name: mysql-database
    volumes:
      - ../backend/database/mysql/dist:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD:-password}
      - MYSQL_USER=${DATABASE_USER:-admin}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD:-password}
      - MYSQL_DATABASE=wp-landing-page
    restart: always
    depends_on:
      - proxy
    labels:
      - traefik.enable=true

  phpmyadmin:
    depends_on:
      - proxy
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.phpmyadmin.entrypoints=web
      - traefik.http.routers.phpmyadmin.entrypoints=websecure
      - traefik.http.routers.phpmyadmin.tls.certresolver=myresolver
