install: configure

configure:

	@echo "⚙️ Configuring Wordpress parameters..."
	wp core install \
		--url="wordpress-landing-page-pbanf.localhost/" \
		--title=landing-page \
		--admin_user=wordpress \
		--admin_password=wordpress \
		--admin_email="test@example.com"
