################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  #
  debug: true
  dashboard: true
  insecure: true
################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    exposedByDefault: false
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.localhost`)"
################################################################
# Traefik Logging
################################################################
log:
  level: INFO

################################################################
# Entrypoint
################################################################
experimental:
  http3: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http3:
      advertisedPort: "443"

################################################################
# Challenge HTTP
################################################################
certificatesResolvers:
  myresolver:
    acme:
      email: serban.paul.91@gmail.com 
      storage: acme.json
      httpChallenge:
        entryPoint: web
