name: CI Deploy to Production
on:
  workflow_dispatch:

jobs:
  test:
    name: Test and Lint
    uses: paulAlexSerban/project-boilerplate-archetype-n-framework/.github/workflows/ci-development.yml@main

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      # Checkout repository
      - name: "☁️ checkout repository"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Cache node_modules to speed up things
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      # Install NodeJS & npm
      - name: "🔧 Setup NodeJS 14.19.1"
        uses: actions/setup-node@v1
        with:
          node-version: 14.19.1

      - name: "🔧 Install npm@latest"
        run: npm i -g npm@latest

      # Install ./frontend/static/prototype dependencies
      - name: "📦  Install Static Prototype dependencies"
        run: npm --prefix frontend/static/prototype install

      # Build ./frontend/static/prototype
      - name: "🏗️  Build static/prototype project"
        run: npm run build:frontend:prototype

      # Package ./frontend/static/prototype
      - name: "📦 Package static/prototype"
        run: "npm run package:static:prototype"
 

      # Deploy ./frontend/static/prototype to GitHub pages
      - name: Deploy static/prototype to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages-prototype
          folder: docs/static/prototype

